name: Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game (ex: com.pubg.imobile)"
        required: false
        default: "com.example.game"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Configure Package Name
      run: |
        if [ -n "${{ github.event.inputs.package_name }}" ]; then
          PKG_NAME="${{ github.event.inputs.package_name }}"
        else
          PKG_NAME="com.example.game"
        fi
        echo "Building for package: $PKG_NAME"
        sed -i "s/moduleDescription = \"/moduleDescription = \"($PKG_NAME) /g" module.gradle
        sed -i "s/com.game.packagename/$PKG_NAME/g" module/src/main/cpp/game.h

    - name: Build with Gradle
      run: ./gradlew :module:assembleRelease

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper
        path: out/*.zip
